%% Select the current procotol 
% (Note: a Brainstorm folder already exists for this subject)
% Get the protocol index
iProtocol = bst_get('Protocol', ProtocolName);
if isempty(iProtocol)
    error(['Unknown protocol: ' ProtocolName]);
end
gui_brainstorm('SetCurrentProtocol', iProtocol);
[sSubject, iSubject] = bst_get('Subject', 'CAT');   
%% IMPORT ===== CORTEX FILE =====
[iCortex1, OldCortexFile1] = import_surfaces(iSubject, ['F:\DataResearch\' PatientName '\Label\fs\lh.pial'], 'ALL', 0);
OldCortexFile1 = OldCortexFile1{1};
[iCortex2, OldCortexFile2] = import_surfaces(iSubject, ['F:\DataResearch\' PatientName '\Label\fs\rh.pial'], 'ALL', 0);
OldCortexFile2 = OldCortexFile2{1};
CortexFile = tess_concatenate({OldCortexFile1, OldCortexFile2}, 'fs_cortex');
NewCortexFile = tess_downsize(CortexFile, 20484, 'iso2mesh');
% Delete separate hemispheres
file_delete({file_fullpath(OldCortexFile1), file_fullpath(OldCortexFile2)}, 1);
NewCortexFile = db_surface_type(NewCortexFile, 'Cortex');
db_reload_subjects(iSubject)
%% Process: Generate BEM surfaces
sFiles = bst_process('CallProcess', 'process_generate_bem', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'nscalp',      1922, ...
    'nouter',      1922, ...
    'ninner',      1922, ...
    'thickness',   4);
%% Process: Create link to raw file
RawFiles = {['F:\DataResearch\' PatientName '\' PatientName '_MEG\' PatientName '.fif']};
sFiles = bst_process('CallProcess', 'process_import_data_raw', sFiles, [], ...
    'subjectname',    SubjectNames{1}, ...
    'datafile',       {RawFiles{1}, 'FIF'}, ...
    'channelreplace', 1, ...
    'channelalign',   1, ...
    'evtmode',        'value');
% Process: Band-pass RAW FILES:1Hz-40Hz
sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
    'sensortypes', 'MEG, EEG', ...
    'highpass',    1, ...
    'lowpass',     40, ...
    'tranband',    0, ...
    'attenuation', 'strict', ...  % 60dB
    'ver',         '2019', ...  % 2019
    'mirror',      0, ...
    'read_all',    0);
% Process: Import Filtered Data
sFiles = bst_process('CallProcess', 'process_import_data_time', sFiles, [], ...
    'subjectname', SubjectNames{1}, ...
    'condition',   '', ...
    'timewindow',  [], ...
    'split',       0, ...
    'ignoreshort', 1, ...
    'usectfcomp',  1, ...
    'usessp',      1, ...
    'freq',        [], ...
    'baseline',    []);

% db_reload_database(iProtocol)
